name: test-3-env
on:
  workflow_dispatch:
jobs:
  dev-job:
    runs-on: ubuntu-latest
    environment: dev-env
    steps:
      - name: run on dev
        run: |
          echo "I am running a job on Dev env"
          echo "show secret"
          echo ${{secrets.MY_DEV_SECRET}} |sed 's/./& /g'
  
  qa-job:
    runs-on: ubuntu-latest
    environment: qa-env
    needs: dev-job
    steps:
      - name: run on qa
        run: |
          echo "I am running a job on QA env"
          echo "show secret"
          echo ${{secrets.MY_DEV_SECRET}} |sed 's/./& /g'
  
  prod-job:
    runs-on: ubuntu-latest
    environment: prod-env
    needs: qa-job
    steps:
      - name: run on prod
        run: |
          echo "I am running a job on Prod env"
    
